d1=input("Enter the Birthday1")
d2=input("Enter the Birthday2")
d3=input("Enter the Birthday3")
d4=input("Enter the Birthday4")
d5=input("Enter the Birthday5")
print(d1)
print(d2)
print(d3)
print(d4)
print(d5)